jdauphant/ansible-role-nginx

- templates/nginx.conf.j2
Hi,
This role is not working with systemd installed on the machine. Here is a fix.
Can you please merge it.
Thanks
> fixing systemd issue when daemon is set to on

- tasks/installation.packages.yml
If else is not specified then the follow error is raised "One or more undefined variables: the inline if-expression on line 1 evaluated to false and no else section was defined."
This was tested using multiple versions of Ansible on a Cent OS target box
> Else statement is require for Jinja2 string

- defaults/main.yml
- handlers/main.yml
- tasks/configuration.yml
- tasks/main.yml
Move the binary and service names to the default variables, so they can be overwritten for custom Nginx builds.
> Move the binary and service names to the default variables

- templates/nginx.conf.j2
If your Nginx config dir is located not in /etc/nginx, the playbook will fail, because of the hardcoded path in the nginx.conf template.
This commit resolves this issue.
> Make use of nginx_conf_dir for includes in nginx.conf.j2

- defaults/main.yml
- templates/nginx.conf.j2
Pid is now configurable, because otherwise it can lead to problems with the init script on custom builds.
> Make the pid directive configurable

- README.md
- defaults/main.yml
- example-vars.yml
- templates/nginx.conf.j2
Implement nginx_events_params and move worker_connections to it.
This allows to implement additional directives in the events module.
> Implement nginx_events_params

- defaults/main.yml
- tasks/installation.packages.yml
This change adds support for openSUSE (13.1 and 13.2 tested) so it ensures the package is installed and the correct user is set.  nginx is not in main openSUSE repository for 13.x but it does appear that it will be / is for tumbleweed and Leap 42.  It is therefore required that a repository for nginx is configured or the packaged is already installed for this module to work when using 13.x.  Not tested on SLES.
> Adding support for openSUSE (User should still define a repo)

- meta/main.yml
Fixed indentation typo in meta/main.yml.  Module will not parse otherwise e.g:
```The error may actually appear before this position: line 18, column 3```
> Fix meta typo

- tasks/installation.packages.yml
Implicit extrapolation of the environment parameter was disabled.
> Fix a compatibility issue with Ansible 2.0

- tasks/configuration.yml
Fixes #75. 
If a user is using the hash merge behavior they can remove the default site by adding it to `nginx_remove_sites` and it will not be re-added after having been removed.
> Allow the default site to be removed with hash merge behavior

- tasks/installation.packages.yml
Addressing this warning: [DEPRECATION WARNING]: Using bare variables for environment is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{foo}}').
> Using the full variable syntax for environment variables

- tasks/configuration.yml
Don't you think it would be better to reload nginx instead of restarting it whenever site configuration is added or changed?
Here is how this troubled me:
- I created a site configuration using this role
- Deployed the new site configuration
- Then I changed the path of my error log
- Deployed the changed site configuration
Expected behaviour:
If I would do this manually, I would make the changes and reload nginx.
Observed:
The role restarted nginx
Side note:
Also, don't you think it should be completely configurable what the user of the role wants to do i.e. reload or restart? The default behaviour can be as it is right now. But I feel the flexibility of being able to change that using variables will be very useful. Thoughts?
> fix task to reload nginx on sites configuration change instead of restart

- tasks/nginx-official-repo.yml
installation.packages task supports setting things like `http_proxy` in
the environment variable, which is used to install packages. This is
useless however if operating behind a proxy and you can’t set the proxy
host when the Ansible playbook tries to get the Nginx official repo key.
> nginx-official-repo should use environment var

- tasks/remove-extras.yml
(using nginx official packages)
We could also fix this using a stat + register, but wanted to keep changes minimal.
> Don't fail when sites-enabled doesn't exist

- tasks/configuration.yml
- tasks/installation.packages.yml
- tasks/remove-extras.yml
- tasks/remove-unwanted.yml
This PR fixes all deprecation warnings introduced in 2.1.0:
`[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{nginx_remove_sites}}'). This 
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`
> Fixed ansible 2.1.0 deprecations

- tasks/configuration.yml
- tasks/ensure-dirs.yml
- tasks/main.yml
This directories are used in ```remove-defaults.yml``` and ```remove-extras.yml```, it of course works even if they are not created yet (if they not exist - it is nothing to remove), but it would be clearer if they would be in place.
> Ensure that sites-enabled/sites-available/ directories exist before execute tasks which use them

- defaults/main.yml
- tasks/configuration.yml
- tasks/ensure-dirs.yml
- tasks/nginx-official-repo.yml
- templates/config_stream.conf.j2
- templates/nginx.conf.j2
- templates/nginx.repo.j2
This adds a `nginx_stream_params` variable to allow configuring the [stream module](http://nginx.org/en/docs/stream/ngx_stream_core_module.html).
Please note that to use this you have to use Nginx 1.9 or a newer one. This adds an `nginx_official_repo_mainline` variable that allows using the mainline repo with the newest stable version.
To use the stream feature you have to have both `nginx_official_repo` and `nginx_official_repo_mainline` set to `True`.
With `nginx_official_repo_mainline` set to `False` (the default) the module behavior does not change and it continues to work with older versions of Nginx.
I'm open to suggestions, so please don't hesitate if you'd like to see something done differently.
> Add support for plain TCP loadbalancing

- tasks/remove-extras.yml
when conf.d has no files, ansible fails with the error because the variable is not a list.
> fix fatal error: "with_items expects a list or a set"

- README.md
- defaults/main.yml
This patch provides configurability for alternative error_log levels as in http://nginx.org/en/docs/ngx_core_module.html#error_log
> add nginx_error_log_level

- tasks/remove-unwanted.yml
It causes a failure running ansible-lint.
> Remove whitespace to fix ansible-lint issue

- tasks/remove-extras.yml
Fix for https://github.com/jdauphant/ansible-role-nginx/issues/118
Only removed unmanaged files (not directories) inside ```conf.d``` so that the ```/etc/nginx/conf.d/stream``` is not added and then removed on each Ansible run.
> GH-118 Fix idempotency and don't delete the conf.d/stream directory.

- defaults/main.yml
- tasks/installation.packages.yml
This minor change allows the caller to set `yum_epel_repo: False` and the role will not try to install epel-release. I have a use case for this because we manage our own repositories that explicitly provide everything that we need without relying on the vagaries of EPEL.
> conditional for epel

- tasks/remove-extras.yml
Avoid deprecation warning for unquoted with_items variable and add an empy array as default for the cases where enabled_sites is not defined (like when running with check-mode/dry-run).
> Avoid deprecation warning

- defaults/main.yml
- templates/nginx.conf.j2
Now we can add more options to main config context, e.g.:
```
user www-data  www-data;
worker_processes  auto;
pid /var/run/nginx.pid;
worker_rlimit_nofile 1024;
include /etc/nginx/modules-enabled/*.conf; # extra option
http {
...
}
```
> Add possibility to additional configuration of the main context

- defaults/main.yml
- templates/nginx.conf.j2
For your comment for yesterday's PR. Now we need to write something like this. 
```
nginx_extra_root_params:
- include /etc/nginx/modules-enabled/*.conf
```
> Use dict for nginx_extra_root_params instead string

- README.md
- tasks/configuration.yml
Two considerations:
1) The current implementation for site config files wraps each site's directives in a `server` block.  While this is arguably the "proper" way to define a site, it prevents standard idioms like including a site's corresponding upstream definition in the same file (for example the standard NGINX/unicorn setup.)  There is real value in combining as site .conf with its upstream, because it allows you to enable/disable/modify a site and its upstreams together.
2) In most cases, the implementor will have an existing .conf file to start with.  For simple configs, it's easy to migrate the NGINX directives to use with this role.  But for more complex configurations, it's not helpful to have to break down a file into an array of directives, hoping in the end this role will …
> Accommodate custom templates for site conf files.

- meta/main.yml
- templates/site.conf.j2
Adding a setting with quotes like this in nginx_sites:
add_header X-XSS-Protection "1; mode=block"
results in the following beeing generated in the config file : 
add_header X-XSS-Protection "1;
mode=block"; 
Some software are having trouble with multiline headers like this.
This is due to the template confusing raw configuration and quoted settings. This PR fixes the issue.
Also, mark FreeBSD versions up to 11.0 as compatible.
> fix settings with quotes in sites template

- tasks/installation.packages.yml
In `meta.yml` this role claims to be compatible with Fedora. This is not the case because recent versions of Fedora use dnf instead of yum for package management. This PR makes this role compatible again by using the general package module.
While doing this changes, I thought that the whole set of installation tasks could be simplified by utilizing the package module and the fact that the package name is almost always just nginx on all platforms. But I leave this up to you to decide if a cleanup is reasonable.
> Compatibility with Fedora

- .travis.yml
- README.md
- defaults/main.yml
- tasks/configuration.yml
- tasks/ensure-dirs.yml
- tasks/remove-unwanted.yml
- test/example-vars.yml
It may be useful to have configuration snippets to include in some other
configuration files (access list, error pages, TLS settings, etc).
> Add support for configuration snippets

- meta/main.yml
I reindented lists as in `galaxy init` template, replaced `categories` to `galaxy_tags` and removed second `\n` at end of file. ansible-lint executed with metacloud/molecule fails tests.
> Fix meta/main syntax

- tasks/ensure-dirs.yml
- templates/nginx.conf.j2
In Debian Stretch (and backported versions of nginx to Jessie), nginx
modules are installed as separate packages and their `load` directives
are moved to `/etc/nginx/modules-enabled/*.conf`.
Closes #166
> Load config from nginx_confdir/modules-enabled

- tasks/configuration.yml
- templates/nginx.conf.j2
Before, nginx_mainline_repo was used to identify a modern enough nginx.
Unfortunately, distros are catching up (e.g. Debian Stretch) and support
the streams module.
If nginx_stream_params or nginx_stream_configs are not empty, a `stream`
block is included in `nginx.conf`.
Closes #160
> Add stream config when one of the vars is defined

- README.md
The variable `nginx_http_params_defaults` was mispelled in the README.
The real variable name, as declared in vars/main.yml is
`nginx_http_default_params`.
> Fix typo in Readme about nginx default var

- handlers/main.yml
always_run will be removed in version 2.4.
> Change depricated 'always_run: yes' to new 'check_mode: no'

- defaults/main.yml
- tasks/ensure-dirs.yml
Using the solution suggested in #174
Now on Debian log directory has correct permissions and shouldnot brake any other distros.
I think everything in /etc/nginx should be owned by root  group rather then nginx_group, why should webscripts group own something in /etc/nginx ?
> Fix CVE-2016-1247 vol2

- tasks/configuration.yml
group on basic auth file have been removed by the previous commit, but
it imply the error
open() "/etc/nginx/auth_basic/foo" failed (14: Permission denied)
Add it back in order to allow nginx to read the basif auth file
> Fix #196 put back the group on basic auth file

- tasks/remove-unwanted.yml
Removing of configs and snippets does not work. This is the same bug that was fixed in #189 that should have been done on these 2 lines also.
> Fix removal of configs and snippets

- templates/nginx.conf.j2
Problem: nginx blocks "{}" could not be used on nginx_http_params since
a semicolon will end up appended, making the configtest to fail
This solution also allows the use of the YAML pipe "|" that which appends a
new line add the end of the string
> Accept blocks on http params

- defaults/main.yml
- tasks/ensure-dirs.yml
This PR will make this role compatible to [dev-sec.nginx-hardening](https://github.com/dev-sec/ansible-nginx-hardening) (step "config should not be worldwide read- or writeable"
) by configuring `nginx_dir_perm: 0750` or `nginx_dir_perm: 0751`.
Nothing will change by default (however this will allow to configure a server more securely while keeping the playbook idempotent).
Currently, the folder-permissions are changed to 0755 by this role, and 0751 by the hardening role. This PR will allow to reconfigure this behaviour.
> Make folder-permissions configurable

- defaults/main.yml
- tasks/configuration.yml
Sometimes it's feasible to leave site not enabled after running nginx role.
E. g. if we want to use nginx role to pre-configure the site, then automatically obtain an ssl certificate via letsencrypt (that requires nginx to be running) and do some additional configuration steps before we finally enable the site.
If a site is mentioned in **nginx_disabled_sites** list, then no link to .conf file is created from 'sites-availiable' to 'sites-enabled'.
> Add possibility to not enable the sites that we don't want to be enabled

- defaults/main.yml
- vars/Debian.yml
- vars/FreeBSD.yml
- vars/Solaris.yml
- vars/empty.yml
This reverts commit b90cc285dda400f617ce2adb7d38b9646accd15c.
@jdauphant I found this morning that there was a new 2.15 release out, because my Nginx provisioning stopped working on CentOS 7:
The problem seem to be that when evaluating this line in `defaults/main.yml`— the only place where `nginx_default_user` is read —we find that it is not defined.
```yml
nginx_log_user: "{% if ansible_os_family == 'Debian' %}root{% else %}{{nginx_user}}{% endif %}"
```
In essence, with the fix to #207 that is release 2.15, this Ansible role now **only** works on Debian (because then default user isn't read at all). 
Kindly proposing to merge this commit-revert as release 2.16.
@krzyzakp Maybe there's a better way of overriding default user?
> Revert "Change user, as which nginx is running (#209)"

- defaults/main.yml
- handlers/main.yml
- tasks/main.yml
- vars/main.yml
Sometimes is not necessary to start Nginx during the role run, so I added the option `nginx_start_service`, by default `true`. I also added `nginx_start_at_boot`, which sets if Nginx should be enabled to start when the machine boots. It defaults to `true` too. The defaults ensure backwards compatibility
The motivation for this change is for those cases where you have a active-passive Nginx servers and you have a 3rd party application starting or stopping them (like heartbeat, pacemaker, or similar). This is important when you have your Nginxs behind (for instance) a AWS ALB, both at the same time, but you cannot serve both at the same time so you keep one down and the other started with some of the 3rd parties utils I mention before.
I understand this can be a very particular case, but …
> Configure start server during the role run and/or at boot

- defaults/main.yml
- tasks/main.yml
Without this option, is impossible to set `nginx_user` outside the role (in the playbook, via group_vars, or wherever), because it is *always* overwritten by the `include_vars`.
`nginx_load_default_vars` is added and defaults to `true`, so it is backwards compatible.
> Add option to include or not vars/{{ansible_os_family}}.yml

- tasks/main.yml
Issue: #186, PR: https://github.com/jdauphant/ansible-role-nginx/pull/188
- One `include` has not been replaced.
- The `import_tasks` is a static include and it won't work if one of the variables in `when` condition will be changed in a runtime.
> #186: Replace obsolete "include" statements by "include_tasks" and "import_tasks"

- README.md
- defaults/main.yml
- tasks/amplify.yml
- tasks/main.yml
We recently had to add support for Nginx Amplify to one of our client's Nginx instances and introduced the necessary steps in our playbooks since it did not seem that this role supports it. We have been using this role for quite a while now and we figured it was time to contribute something back :).
The tasks were based off of Nginx's official Ansible role (which does support Amplify), and also the recommended steps when attempting to add a new server on the Amplify website.
If there are any points of feedback with respect to the PR just let us know :).
> Support Nginx Amplify

- handlers/main.yml
Explicitly setting the nginx configuration file in the "check nginx configuration" handler. This is required whenever you're not using the default value.
> Setting the nginx configuration file in the "check nginx configuration" handler

- .travis.yml
- tasks/amplify.yml
- tasks/configuration.yml
- tasks/installation.packages.yml
- tasks/selinux.yml
- vars/Debian.yml
- vars/RedHat.yml
- vars/main.yml
* Remving travis deprecation warning - Moving from "--sudo" to "--become"
* For further details take a look at: https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.7.html#using-a-loop-on-a-package-module-via-squash-actions
> Fixing Ansible 2.7.0 deprication warnings

- defaults/main.yml
- tasks/configuration.yml
- templates/module.conf.j2
Dear Julien,
I have added few changes to your project "ansible-role-nginx" and add support to declare modules. 
My example playbook : 
```yaml
- hosts: all
roles:
- role: ansible-role-nginx
nginx_http_params:
- sendfile on
- access_log /var/log/nginx/access.log
- error_log /var/log/nginx/error.log
- include snippets/geoip.conf
nginx_module_configs:
- ngx_http_geoip_module
nginx_snippets:
geoip:
-    geoip_country /usr/share/GeoIP/GeoIP.dat;
map $geoip_country_code $allowed_country {
default yes;
IR no;
CN no;
}
```
And next I just add geoip functions into virtual hosts. 
Thanks,
Dmitry
> Add support to declare nginx modules in config file

- README.md
- tasks/configuration.yml
I have fixed modules definition (correct path in RHEL & CentOS) and add few words into README.md about the feature.
> fix modules definition and add README section about this feature

- tasks/configuration.yml
This fixes a small typo and also restricts the configuring modules a little further so that it only applies when the EPEL based version of Nginx is installed (this is the default).
> Fix typo in modules config and restrict to EPEL (#232)

- tasks/configuration.yml
After I ran this role on debian buster I noticed `/etc/nginx/mime.types` was missing. I'm unsure why. This PR downloads it from nginx's github if it is missing. I did not see that anyone else has run into the problem but we can keep this here as an idea or possible solution if we discover many others have the problem.
Thanks for having a look.
```sh
ansible-galaxy remove jdauphant.nginx
ansible-galaxy install 'git+https://github.com/youreadforme/ansible-role-nginx.git,missing-mime-types'
```
`./nginx-test.yml`
```yml
- name: nginx test
hosts: all
become: true
roles:
- role: ansible-role-nginx
```
`./Vagrant file`
```ruby
Vagrant.configure("2") do |config|
config.vm.hostname = "nginx-test"
config.vm.box = "debian/buster64"
config.vm.box_check_update = false
config.vm.provider "virtualbox" …
```
> Download mime.types file if it's missing

- tasks/configuration.yml
similarly to `sites` configuration `stream` configuration, allow the usage of custom templates to define `conf.d/*.conf` files.
> configuration: allow templates for conf.d independent files

- meta/main.yml
- tasks/amplify.yml
- tasks/configuration.yml
- tasks/ensure-dirs.yml
- tasks/main.yml
- tasks/remove-defaults.yml
- tasks/remove-extras.yml
- tasks/remove-unwanted.yml
- tasks/selinux.yml
Each commit fixes one rule violation.
> Fix for #242 Stick to ansible-lint rules.

- tasks/main.yml
- vars/Debian-12.yml
Added a functionality to the task in main.yml that includes the os dependent vars whereby you can speficie the os version of the vars that you want. The corresponding file(s) for that os version must be created in the vars folder. The compatibility with Debian12 was also created in the vars folder.
> Newer os compatiblity with os dependent vars
